# OUTPUT_LANG_INDEX start from 0
generator-localization:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1hSGRpRE_vx--2SC3Mo6ZvivCkS-nyayOhHg2ncTbBtg GID_ID=user OUTPUT_FOLDER=../public/locales/en/common.json
	
